[profile.default]
src = "src"
out = "artifacts"
libs = [
    "lib",
    "node_modules",
]
remappings = ["@openzeppelin/=node_modules/@openzeppelin/"]
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
alfajores = "${ALFAJORES_RPC_URL}"
