[profile.default]
src = "src"
out = "artifacts"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
solc_version = "0.8.20"

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/"
]

[rpc_endpoints]
mainnet = "https://forno.celo.org/"
alfajores = "https://alfajores-forno.celo-testnet.org/"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.celoscan.io/api" }
alfajores = { key = "${ETHERSCAN_API_KEY}", url = "https://api-alfajores.celoscan.io/api" }
